version: '3.8'

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "container:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${qb_UI}
      - TORRENTING_PORT=${qb_TOR}
    volumes:
      - ${CONFIG}/qbittorrent:/config
      - ${STORAGE}/data:/data
    labels:
      - deunhealth.restart.on.unhealthy= "true"
    restart: unless-stopped
    # HEALTH CHECK #
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    network_mode: "container:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${nzb_UI}
      - NZBGET_USER=${nzb_USER}
      - NZBGET_PASS=${nzb_PASS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/nzbget:/config
      - ${STORAGE}/data:/data
    restart: unless-stopped
