version: '3.8'

networks:
  my-bridge:
    external: 
      name: my-bridge
  servarr:
    external:
      name: servarr

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    networks:
      my-bridge:
        ipv4_address: 10.0.1.3
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      # - PLEX_CLAIM= #optional
    ports:
      - 32400:${plex_SERV}
      - 8324:${plex_ROKU}
      - 32469:${plex_DLNA}
    devices:
      - /dev/dri:/dev/dri # QuickSync
    volumes:
      - ${CONFIG}/plex:/config
      - ${STORAGE}/data/movies:/movies:ro
      - ${STORAGE}/data/shows:/shows:ro
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    networks:
      my-bridge:
        ipv4_address: 10.0.1.103
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/overseer:/config
      - ${STORAGE}/data:/data:ro
    ports:
      - 5055:${overseer_UI}
    restart: unless-stopped

  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    networks:
      my-bridge:
        ipv4_address: 10.0.1.2
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8096:${jf_UI}
    devices:
      - /dev/dri:/dev/dri # QuickSync
    volumes:
      - ${CONFIG}/jellyfin:/config
      - ${STORAGE}/data:/data:ro
    restart: unless-stopped

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    networks:
      my-bridge:
        ipv4_address: 10.0.1.102
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/jellyseerr:/app/config
    ports:
      - 5055:${jseerr_UI}
    restart: unless-stopped