version: '3.8'

networks:

  servarr:
    external:
      name: servarr # subnet 10.1.1.0/24

services:

  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    networks:
      servarr:
        ipv4_address: 10.0.1.3
    ports:
      - 8096:${jf_UI}
    devices:
      - /dev/dri:/dev/dri # QuickSync
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/jellyfin:/config
      - ${STORAGE}/data:/data:ro
    restart: unless-stopped

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    networks:
      servarr:
        ipv4_address: 10.0.1.103
    ports:
      - 5055:${jseerr_UI}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/jellyseerr:/app/config
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    networks:
      servarr:
        ipv4_address: 10.0.1.4
    ports:
      - 32400:${plex_SERV}
      - 8324:${plex_ROKU}
      - 32469:${plex_DLNA}
    devices:
      - /dev/dri:/dev/dri # QuickSync
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      # - PLEX_CLAIM= #optional
    volumes:
      - ${CONFIG}/plex:/config
      - ${STORAGE}/data/movies:/movies:ro
      - ${STORAGE}/data/shows:/shows:ro
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    networks:
      servarr:
        ipv4_address: 10.0.1.104
    ports:
      - 45055:${overseerr_UI}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/overseer:/config
      - ${STORAGE}/data:/data:ro
    restart: unless-stopped
