version: '3.8'

networks:
  my-bridge:
    external:
      name: my-bridge # subnet 10.1.0.0/24

  servarr:
    external:
      name: servarr # subnet 10.1.1.0/24

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    networks:
      my-bridge:
        ipv4_address: 10.1.0.100
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/heimdall:/config
    ports:
      - "13080:80"
      - "13443:443"
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    networks:
      servarr:
        ipv4_address: 10.1.1.2
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:${qb_UI}
      - 6881:${qp_TOR}
      - 6789:${nzb_UI}
      - 9696:${prowl_UI}
    volumes:
      - ${CONFIG}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${PRIVATEKEY}
      - WIREGUARD_ADDRESSES=${ADDRESS}
      - WIREGUARD_COUNTRIES=United_States
      - WIREGUARD_CITIES=Detroit
      - HEALTH_VPN_DURATION_INITIAL=120s
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      timeout: 20s
      retries: 5
    restart: unless-stopped

  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    network_mode: "none"
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always