version: '3.8'

networks:
  my-bridge:
    external: 
      name: my-bridge
  servarr:
    external:
      name: servarr

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      servarr:
        ipv4_address: 10.1.1.2
    ports:
      - ${qb_UI}:8080 # qbittorrent web interface
      - ${qb_TOR}:6881 # qbittorrent torrent port
      - ${nzb_UI}:6789 # nzbget
      - ${prowl_UI}:9696 # prowlarr
    volumes:
      - ${CONFIG}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${PRIVATEKEY}
      - WIREGUARD_ADDRESSES=${ADDRESS}
      - WIREGUARD_COUNTRIES=United_States
      - WIREGUARD_CITIES=Detroit
      - HEALTH_VPN_DURATION_INITIAL=120s
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      timeout: 20s
      retries: 5
    restart: unless-stopped

  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    network_mode: "none"
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ=${TZ}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: lscr.io/linuxserver/nginx
    container_name: nginx
    networks:
      - my-bridge
      - servarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/nginx:/config